var content = {
    "projects": {
        "ABOUT": {
            "images": [
                "./content/ABOUT/rotate_cropped_image2 (3rd copy).png",
                "./content/ABOUT/rotate_cropped_image2 (4th copy).png",
                "./content/ABOUT/rotate_cropped_image2 (5th copy).png",
                "./content/ABOUT/rotate_cropped_image2 (6th copy).png",
                "./content/ABOUT/rotate_cropped_image2 (7th copy).png",
                "./content/ABOUT/rotate_cropped_image2 (8th copy).png",
                "./content/ABOUT/rotate_cropped_image2 (another copy).png",
                "./content/ABOUT/rotate_cropped_image2 (copy).png"
            ],
            "html": "hi there, my name is ssadasadad",
            "tags": [
                "#about,<br> #textile,<br> #about,<br> #website"
            ],
            "date": "2/3/2021"
        },
        "Advanced Textile Materials: Enhancing Performance and Durability (another copy)": {
            "images": [
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/1 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/1.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/11.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/12.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/13.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/14.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/15.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/16.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/17 (3rd copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/17 (another copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/17 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/17.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/18.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/19.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/2 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/2.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/20.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/21 (3rd copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/21 (another copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/21 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/21.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/22.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (3rd copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (4th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (5th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (6th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (7th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (another copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/4 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/4.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/5 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/5.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/6 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/6.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/7 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/7.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/8 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/8.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9 (3rd copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9 (4th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9 (5th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9 (another copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/aaa.jpg"
            ],
            "html": "Lorei quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentiumesentiuam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentiumesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br><br><h2>section</h2><br>esentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentiumesentium  ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br><br>esentium animi quibusdam repud repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br><br>esentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentiumum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br>esentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br><br><u></u><br><br>esentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id p animi quibusdam repudiandae.<br><br>praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore <br><br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br><br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad",
            "tags": [
                "#textile,<br> #materials,<br> #performance,<br> #research"
            ],
            "date": "2/3/2023"
        },
        "project 1": {
            "images": [
                "./content/project 1/rotate_cropped_image3 (3rd copy).png",
                "./content/project 1/rotate_cropped_image3 (4th copy).png",
                "./content/project 1/rotate_cropped_image3 (5th copy).png",
                "./content/project 1/rotate_cropped_image3 (6th copy).png",
                "./content/project 1/rotate_cropped_image3 (7th copy).png",
                "./content/project 1/rotate_cropped_image3 (8th copy).png",
                "./content/project 1/rotate_cropped_image3 (9th copy).png",
                "./content/project 1/rotate_cropped_image3 (another copy).png",
                "./content/project 1/rotate_cropped_image3 (copy).png",
                "./content/project 1/rotate_cropped_image3.png"
            ],
            "html": "beke tekst he",
            "tags": [
                "#project,<br> #mooi,<br> #1,<br> #2,<br> #3,<br> #4,<br> #5,<br> #5,<br> #6,<br> #7,<br> #8,<br> #89,<br> #90,<br> #90,<br> #knap"
            ],
            "date": "7 january 2024"
        },
        "project 2": {
            "images": [
                "./content/project 2/rotate_cropped_image2.png",
                "./content/project 2/rotate_cropped_image3.png"
            ],
            "html": "here is just the place for some text",
            "tags": [
                "#testing,<br> #jfdfd,<br> #dsfdsf,<br> #dfdfdf,<br> #dfdfdfre,<br> #ewwdswed"
            ],
            "date": "ddddddddddddddddddddddd"
        }
    },
    "allTags": [
        "<span class='filter' data-filter='1'>#1</span>",
        "<span class='filter' data-filter='2'>#2</span>",
        "<span class='filter' data-filter='3'>#3</span>",
        "<span class='filter' data-filter='4'>#4</span>",
        "<span class='filter' data-filter='5'>#5</span>",
        "<span class='filter' data-filter='6'>#6</span>",
        "<span class='filter' data-filter='7'>#7</span>",
        "<span class='filter' data-filter='8'>#8</span>",
        "<span class='filter' data-filter='89'>#89</span>",
        "<span class='filter' data-filter='90'>#90</span>",
        "<span class='filter' data-filter='about'>#about</span>",
        "<span class='filter' data-filter='dfdfdf'>#dfdfdf</span>",
        "<span class='filter' data-filter='dfdfdfre'>#dfdfdfre</span>",
        "<span class='filter' data-filter='dsfdsf'>#dsfdsf</span>",
        "<span class='filter' data-filter='ewwdswed'>#ewwdswed</span>",
        "<span class='filter' data-filter='jfdfd'>#jfdfd</span>",
        "<span class='filter' data-filter='knap'>#knap</span>",
        "<span class='filter' data-filter='materials'>#materials</span>",
        "<span class='filter' data-filter='mooi'>#mooi</span>",
        "<span class='filter' data-filter='performance'>#performance</span>",
        "<span class='filter' data-filter='project'>#project</span>",
        "<span class='filter' data-filter='research'>#research</span>",
        "<span class='filter' data-filter='testing'>#testing</span>",
        "<span class='filter' data-filter='textile'>#textile</span>",
        "<span class='filter' data-filter='website'>#website</span>"
    ],
    "barContent": [
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./project 1.html'>project 1</a>&ensp;&ensp;",
        "<a href='./project 2.html'>project 2</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./project 1.html'>project 1</a>&ensp;&ensp;",
        "<a href='./project 2.html'>project 2</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./project 1.html'>project 1</a>&ensp;&ensp;",
        "<a href='./project 2.html'>project 2</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./project 1.html'>project 1</a>&ensp;&ensp;",
        "<a href='./project 2.html'>project 2</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./project 1.html'>project 1</a>&ensp;&ensp;",
        "<a href='./project 2.html'>project 2</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./project 1.html'>project 1</a>&ensp;&ensp;",
        "<a href='./project 2.html'>project 2</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./project 1.html'>project 1</a>&ensp;&ensp;",
        "<a href='./project 2.html'>project 2</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./project 1.html'>project 1</a>&ensp;&ensp;",
        "<a href='./project 2.html'>project 2</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./project 1.html'>project 1</a>&ensp;&ensp;",
        "<a href='./project 2.html'>project 2</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./project 1.html'>project 1</a>&ensp;&ensp;",
        "<a href='./project 2.html'>project 2</a>&ensp;&ensp;"
    ]
}