var content = {
    "projects": {
        "3D Printing of Textiles (3rd copy)": {
            "images": [
                "./content/3D Printing of Textiles (3rd copy)/1.png",
                "./content/3D Printing of Textiles (3rd copy)/2.jpg",
                "./content/3D Printing of Textiles (3rd copy)/3.jpg",
                "./content/3D Printing of Textiles (3rd copy)/4.jpg",
                "./content/3D Printing of Textiles (3rd copy)/5.jpg"
            ],
            "html": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.<br><br>praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore <br><br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br><br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad",
            "tags": [
                "#textile,<br> #3d printing,<br> #red,<br> #big,<br> #paper,<br> #research"
            ],
            "date": "2/3/2023"
        },
        "ABOUT": {
            "images": [
                "./content/ABOUT/rotate_cropped_image2 (3rd copy).png",
                "./content/ABOUT/rotate_cropped_image2 (4th copy).png",
                "./content/ABOUT/rotate_cropped_image2 (5th copy).png",
                "./content/ABOUT/rotate_cropped_image2 (6th copy).png",
                "./content/ABOUT/rotate_cropped_image2 (7th copy).png",
                "./content/ABOUT/rotate_cropped_image2 (8th copy).png",
                "./content/ABOUT/rotate_cropped_image2 (another copy).png",
                "./content/ABOUT/rotate_cropped_image2 (copy).png"
            ],
            "html": "hi there, my name is ssadasadad",
            "tags": [
                "#about,<br> #textile,<br> #about,<br> #website"
            ],
            "date": "2/3/2021"
        },
        "Advanced Textile Materials: Enhancing Performance and Durability (another copy)": {
            "images": [
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/1 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/1.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/11.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/12.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/13.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/14.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/15.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/16.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/17 (3rd copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/17 (another copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/17 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/17.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/18.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/19.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/2 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/2.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/20.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/21 (3rd copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/21 (another copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/21 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/21.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/22.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (3rd copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (4th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (5th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (6th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (7th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (another copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/3.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/4 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/4.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/5 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/5.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/6 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/6.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/7 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/7.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/8 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/8.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9 (3rd copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9 (4th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9 (5th copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9 (another copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9 (copy).jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/9.jpg",
                "./content/Advanced Textile Materials: Enhancing Performance and Durability (another copy)/aaa.jpg"
            ],
            "html": "Lorei quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentiumesentiuam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentiumesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br><br><h2>section</h2><br>esentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentiumesentium  ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br><br>esentium animi quibusdam repud repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br><br>esentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentiumum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br>esentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br><br><u></u><br><br>esentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id p animi quibusdam repudiandae.<br><br>praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore <br><br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br><br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad",
            "tags": [
                "#textile,<br> #materials,<br> #performance,<br> #research"
            ],
            "date": "2/3/2023"
        },
        "Biodegradable and Eco-friendly Textile Production Methods (another copy)": {
            "images": [
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_248.jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_252 (copy).jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_253 (3rd copy).jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_253 (another copy).jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_253 (copy).jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_253.jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_62 (3rd copy).jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_62 (another copy).jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_62 (copy).jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_62.jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_9 (another copy).jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/rsz_h930_1_9 (copy).jpg",
                "./content/Biodegradable and Eco-friendly Textile Production Methods (another copy)/x.jpg"
            ],
            "html": "Lorei quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium anim<br>esentium animi quibusdam repud repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br><br>esentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentiumum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br>esentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium<br>mi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore <br><br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br>voluptatem exonsectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br><br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad",
            "tags": [
                "#textile,<br> #materials,<br> #bio,<br> #research,<br> #big"
            ],
            "date": "2/3/2023"
        },
        "Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)": {
            "images": [
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/aaa (3rd copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/aaa (4th copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/aaa (another copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/aaa (copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/aaa.jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/asd (3rd copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/asd (4th copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/asd (another copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/asd (copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/asd.jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/rsz_h930_1_248 (another copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/rsz_h930_1_248 (copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/rsz_h930_1_252 (3rd copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/rsz_h930_1_252 (4th copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/rsz_h930_1_252.jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/rsz_h930_1_62 (3rd copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/rsz_h930_1_62 (4th copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/rsz_h930_1_62 (another copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/rsz_h930_1_62 (copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/rsz_h930_1_62.jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/z (copy).jpg",
                "./content/Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)/z.jpg"
            ],
            "html": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.<br><br>praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad",
            "tags": [
                "#textile,<br> #eco,<br> #smart,<br> #favrib,<br> #integration,<br> #research,<br> #electronics,<br> #red"
            ],
            "date": "1/3/2022"
        },
        "Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)": {
            "images": [
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/aaa (3rd copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/aaa (4th copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/aaa (another copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/aaa (copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/aaa.jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/asd (3rd copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/asd (4th copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/asd (another copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/asd (copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/asd.jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/rsz_h930_1_248 (another copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/rsz_h930_1_248 (copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/rsz_h930_1_252 (3rd copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/rsz_h930_1_252.jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/rsz_h930_1_62 (3rd copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/rsz_h930_1_62 (4th copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/rsz_h930_1_62 (another copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/rsz_h930_1_62 (copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/rsz_h930_1_62.jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)/w.jpg"
            ],
            "html": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi qumnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium",
            "tags": [
                "#textile,<br> #red,<br> #research"
            ],
            "date": "1/1/2013"
        },
        "Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)": {
            "images": [
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)/rsz_h930_1_248 (another copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)/rsz_h930_1_62 (3rd copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)/rsz_h930_1_62 (4th copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)/rsz_h930_1_62 (another copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)/rsz_h930_1_62 (copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)/rsz_h930_1_62.jpg"
            ],
            "html": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi qumnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium",
            "tags": [
                "#textile,<br> #red,<br> #research"
            ],
            "date": "1/1/2013"
        },
        "Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)": {
            "images": [
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/aaa (3rd copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/aaa (4th copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/aaa (another copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/aaa (copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/aaa.jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/asd (3rd copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/asd (4th copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/asd (another copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/asd (copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/asd.jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/rsz_h930_1_248 (another copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/rsz_h930_1_248 (copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/rsz_h930_1_252 (3rd copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/rsz_h930_1_252.jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/rsz_h930_1_62 (3rd copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/rsz_h930_1_62 (4th copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/rsz_h930_1_62 (another copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/rsz_h930_1_62 (copy).jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/rsz_h930_1_62.jpg",
                "./content/Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)/w.jpg"
            ],
            "html": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi qumnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium",
            "tags": [
                "#textile,<br> #red,<br> #research"
            ],
            "date": "1/1/2013"
        },
        "foobar": {
            "images": [
                "./content/foobar/2 (3rd copy).jpg",
                "./content/foobar/2 (another copy).jpg",
                "./content/foobar/2 (copy).jpg",
                "./content/foobar/2.jpg",
                "./content/foobar/3 (3rd copy).jpg",
                "./content/foobar/3 (another copy).jpg",
                "./content/foobar/3 (copy).jpg",
                "./content/foobar/3.jpg",
                "./content/foobar/4.jpg",
                "./content/foobar/5.jpg",
                "./content/foobar/x.png"
            ],
            "html": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.<br><br>praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore <br><br>voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad<br>volupt<br>ing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad",
            "tags": [
                "#nano,<br> #3d printing,<br> #red,<br> #texttile,<br> #nano,<br> #technology"
            ],
            "date": "2/333/2023"
        },
        "student work": {
            "images": [
                "./content/student work/11.jpg",
                "./content/student work/12.jpg",
                "./content/student work/13.jpg",
                "./content/student work/14.jpg",
                "./content/student work/15.jpg",
                "./content/student work/16.jpg",
                "./content/student work/17.jpg",
                "./content/student work/3.jpg",
                "./content/student work/4.jpg",
                "./content/student work/5.jpg",
                "./content/student work/6.jpg",
                "./content/student work/7.jpg",
                "./content/student work/8.jpg",
                "./content/student work/9.jpg"
            ],
            "html": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus tot repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qsdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.<br><br>praesee.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolorsdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.<br><br>praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus ei.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolorsdam repudiandae.Lorem ipsum dolor sit, amit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad",
            "tags": [
                "#textile,<br> #eco,<br> #smart,<br> #student"
            ],
            "date": "1/3/2024"
        },
        "student work (3rd copy)": {
            "images": [
                "./content/student work (3rd copy)/11.jpg",
                "./content/student work (3rd copy)/12.jpg",
                "./content/student work (3rd copy)/13.jpg",
                "./content/student work (3rd copy)/14.jpg",
                "./content/student work (3rd copy)/15.jpg",
                "./content/student work (3rd copy)/16.jpg",
                "./content/student work (3rd copy)/3.jpg",
                "./content/student work (3rd copy)/4.jpg",
                "./content/student work (3rd copy)/5.jpg",
                "./content/student work (3rd copy)/6.jpg",
                "./content/student work (3rd copy)/7.jpg",
                "./content/student work (3rd copy)/8.jpg",
                "./content/student work (3rd copy)/9.jpg",
                "./content/student work (3rd copy)/x.jpg"
            ],
            "html": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus tot repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qsdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.<br><br>praesee.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolorsdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.<br><br>praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus ei.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolorsdam repudiandae.Lorem ipsum dolor sit, amit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius omnis tempore ut repellendus molestias impedit quaerat dolore voluptatem ex, magni quas qui id praesentium animi quibusdam repudiandae.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus totam minus eius <br>assadasadad",
            "tags": [
                "#textile,<br> #eco,<br> #smart,<br> #student"
            ],
            "date": "1/3/2024"
        }
    },
    "allTags": [
        "<span class='filter' data-filter='3d printing'>#3d printing</span>",
        "<span class='filter' data-filter='about'>#about</span>",
        "<span class='filter' data-filter='big'>#big</span>",
        "<span class='filter' data-filter='bio'>#bio</span>",
        "<span class='filter' data-filter='eco'>#eco</span>",
        "<span class='filter' data-filter='electronics'>#electronics</span>",
        "<span class='filter' data-filter='favrib'>#favrib</span>",
        "<span class='filter' data-filter='integration'>#integration</span>",
        "<span class='filter' data-filter='materials'>#materials</span>",
        "<span class='filter' data-filter='nano'>#nano</span>",
        "<span class='filter' data-filter='paper'>#paper</span>",
        "<span class='filter' data-filter='performance'>#performance</span>",
        "<span class='filter' data-filter='red'>#red</span>",
        "<span class='filter' data-filter='research'>#research</span>",
        "<span class='filter' data-filter='smart'>#smart</span>",
        "<span class='filter' data-filter='student'>#student</span>",
        "<span class='filter' data-filter='technology'>#technology</span>",
        "<span class='filter' data-filter='textile'>#textile</span>",
        "<span class='filter' data-filter='texttile'>#texttile</span>",
        "<span class='filter' data-filter='website'>#website</span>"
    ],
    "barContent": [
        "<a href='./3D Printing of Textiles (3rd copy).html'>3D Printing of Textiles (3rd copy)</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./Biodegradable and Eco-friendly Textile Production Methods (another copy).html'>Biodegradable and Eco-friendly Textile Production Methods (another copy)</a>&ensp;&ensp;",
        "<a href='./Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy).html'>Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)</a>&ensp;&ensp;",
        "<a href='./foobar.html'>foobar</a>&ensp;&ensp;",
        "<a href='./student work.html'>student work</a>&ensp;&ensp;",
        "<a href='./student work (3rd copy).html'>student work (3rd copy)</a>&ensp;&ensp;",
        "<a href='./3D Printing of Textiles (3rd copy).html'>3D Printing of Textiles (3rd copy)</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./Biodegradable and Eco-friendly Textile Production Methods (another copy).html'>Biodegradable and Eco-friendly Textile Production Methods (another copy)</a>&ensp;&ensp;",
        "<a href='./Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy).html'>Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)</a>&ensp;&ensp;",
        "<a href='./foobar.html'>foobar</a>&ensp;&ensp;",
        "<a href='./student work.html'>student work</a>&ensp;&ensp;",
        "<a href='./student work (3rd copy).html'>student work (3rd copy)</a>&ensp;&ensp;",
        "<a href='./3D Printing of Textiles (3rd copy).html'>3D Printing of Textiles (3rd copy)</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./Biodegradable and Eco-friendly Textile Production Methods (another copy).html'>Biodegradable and Eco-friendly Textile Production Methods (another copy)</a>&ensp;&ensp;",
        "<a href='./Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy).html'>Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)</a>&ensp;&ensp;",
        "<a href='./foobar.html'>foobar</a>&ensp;&ensp;",
        "<a href='./student work.html'>student work</a>&ensp;&ensp;",
        "<a href='./student work (3rd copy).html'>student work (3rd copy)</a>&ensp;&ensp;",
        "<a href='./3D Printing of Textiles (3rd copy).html'>3D Printing of Textiles (3rd copy)</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./Biodegradable and Eco-friendly Textile Production Methods (another copy).html'>Biodegradable and Eco-friendly Textile Production Methods (another copy)</a>&ensp;&ensp;",
        "<a href='./Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy).html'>Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)</a>&ensp;&ensp;",
        "<a href='./foobar.html'>foobar</a>&ensp;&ensp;",
        "<a href='./student work.html'>student work</a>&ensp;&ensp;",
        "<a href='./student work (3rd copy).html'>student work (3rd copy)</a>&ensp;&ensp;",
        "<a href='./3D Printing of Textiles (3rd copy).html'>3D Printing of Textiles (3rd copy)</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./Biodegradable and Eco-friendly Textile Production Methods (another copy).html'>Biodegradable and Eco-friendly Textile Production Methods (another copy)</a>&ensp;&ensp;",
        "<a href='./Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy).html'>Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)</a>&ensp;&ensp;",
        "<a href='./foobar.html'>foobar</a>&ensp;&ensp;",
        "<a href='./student work.html'>student work</a>&ensp;&ensp;",
        "<a href='./student work (3rd copy).html'>student work (3rd copy)</a>&ensp;&ensp;",
        "<a href='./3D Printing of Textiles (3rd copy).html'>3D Printing of Textiles (3rd copy)</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./Biodegradable and Eco-friendly Textile Production Methods (another copy).html'>Biodegradable and Eco-friendly Textile Production Methods (another copy)</a>&ensp;&ensp;",
        "<a href='./Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy).html'>Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)</a>&ensp;&ensp;",
        "<a href='./foobar.html'>foobar</a>&ensp;&ensp;",
        "<a href='./student work.html'>student work</a>&ensp;&ensp;",
        "<a href='./student work (3rd copy).html'>student work (3rd copy)</a>&ensp;&ensp;",
        "<a href='./3D Printing of Textiles (3rd copy).html'>3D Printing of Textiles (3rd copy)</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./Biodegradable and Eco-friendly Textile Production Methods (another copy).html'>Biodegradable and Eco-friendly Textile Production Methods (another copy)</a>&ensp;&ensp;",
        "<a href='./Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy).html'>Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)</a>&ensp;&ensp;",
        "<a href='./foobar.html'>foobar</a>&ensp;&ensp;",
        "<a href='./student work.html'>student work</a>&ensp;&ensp;",
        "<a href='./student work (3rd copy).html'>student work (3rd copy)</a>&ensp;&ensp;",
        "<a href='./3D Printing of Textiles (3rd copy).html'>3D Printing of Textiles (3rd copy)</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./Biodegradable and Eco-friendly Textile Production Methods (another copy).html'>Biodegradable and Eco-friendly Textile Production Methods (another copy)</a>&ensp;&ensp;",
        "<a href='./Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy).html'>Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)</a>&ensp;&ensp;",
        "<a href='./foobar.html'>foobar</a>&ensp;&ensp;",
        "<a href='./student work.html'>student work</a>&ensp;&ensp;",
        "<a href='./student work (3rd copy).html'>student work (3rd copy)</a>&ensp;&ensp;",
        "<a href='./3D Printing of Textiles (3rd copy).html'>3D Printing of Textiles (3rd copy)</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./Biodegradable and Eco-friendly Textile Production Methods (another copy).html'>Biodegradable and Eco-friendly Textile Production Methods (another copy)</a>&ensp;&ensp;",
        "<a href='./Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy).html'>Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)</a>&ensp;&ensp;",
        "<a href='./foobar.html'>foobar</a>&ensp;&ensp;",
        "<a href='./student work.html'>student work</a>&ensp;&ensp;",
        "<a href='./student work (3rd copy).html'>student work (3rd copy)</a>&ensp;&ensp;",
        "<a href='./3D Printing of Textiles (3rd copy).html'>3D Printing of Textiles (3rd copy)</a>&ensp;&ensp;",
        "<a href='./ABOUT.html'>ABOUT</a>&ensp;&ensp;",
        "<a href='./Advanced Textile Materials: Enhancing Performance and Durability (another copy).html'>Advanced Textile Materials: Enhancing Performance and Durability (another copy)</a>&ensp;&ensp;",
        "<a href='./Biodegradable and Eco-friendly Textile Production Methods (another copy).html'>Biodegradable and Eco-friendly Textile Production Methods (another copy)</a>&ensp;&ensp;",
        "<a href='./Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy).html'>Exploring Smart Textiles: Integration of Electronics and Fabrics (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (4th copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (another copy)</a>&ensp;&ensp;",
        "<a href='./Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy).html'>Innovative Textile Manufacturing Techniques for Sustainable Fashion (copy)</a>&ensp;&ensp;",
        "<a href='./foobar.html'>foobar</a>&ensp;&ensp;",
        "<a href='./student work.html'>student work</a>&ensp;&ensp;",
        "<a href='./student work (3rd copy).html'>student work (3rd copy)</a>&ensp;&ensp;"
    ]
}